-- EDA


SELECT*FROM customers;
SELECT * FROM restaurants;
SELECT * FROM orders;
SELECT * FROM riders;
SELECT * FROM deliveries;

-- Handling Null values

SELECT COUNT(*) FROM customers
WHERE 
    customer_name IS NULL
    OR
    reg_date IS NULL

SELECT COUNT(*) FROM restaurants
WHERE 
    restaurant_name IS NULL
    OR
    city IS NULL
    OR
    opening_hours IS NULL

SELECT COUNT(*) FROM orders
WHERE 
    order_item IS NULL
    OR
    order_date IS NULL
    OR
    order_time IS NULL
    OR
    order_status IS NULL
    OR 
    total_amount IS NULL

SELECT COUNT(*) FROM riders
WHERE 
    rider_name IS NULL
    OR
    sign_up IS NULL


SELECT COUNT(*) FROM deliveries
WHERE 
    delivery_status IS NULL
    OR
    delivery_time IS NULL

-- -------------------------
-- ANALYSIS & REPORTS
-- -------------------------

--  Q1. Top 5 Most Frequently Ordered Dishes 
-- Question:  Write a query to find the top 5 most frequently ordered dishes by the customer "Arjun Mehta" in the last 1 year. 

-- join customers and orders
-- filter for last one year
-- filter 'arjun mehta'
-- group by customers_id, dishes, count of the customer

SSELECT 
    c.customer_id,
    c.customer_name,
    o.order_item as dishes,
    COUNT(*) as total_orders
FROM orders as o
JOIN
customers as c
ON c.customer_id = o.customer_id
WHERE 
    o.order_date >= DATE '2025-01-25' - INTERVAL '1 Year'
GROUP BY 1, 2, 3




-- Q2. Popular Time Slots 
-- Question:  Identify the time slots during which the most orders are placed, based on 2-hour intervals. 

-- Q3. Order Value Analysis 
-- Question: Find the average order value (AOV) per customer who has placed more than 750 orders. Return: customer_name, aov (average order value). 

-- Q4. High-Value Customers 
-- Question: List the customers who have spent more than 100K in total on food orders. Return: customer_name, customer_id. 


-- Q5. Orders Without Delivery 
-- Question: Write a query to find orders that were placed but not delivered. 
-- Return: restaurant_name, city, and the number of not delivered orders. 

-- Q6. Restaurant Revenue Ranking
-- Question: Rank restaurants by their total revenue from the last year. 
-- Return: restaurant_name, total_revenue, and their rank within their city. 

-- Q7. Most Popular Dish by City 
-- Question: Identify the most popular dish in each city based on the number of orders. 

-- Q8. Customer Churn 
-- Question:  Find customers who haven’t placed an order in 2024 but did in 2023. 

-- Q9. Cancellation Rate Comparison 
-- Question:  Calculate and compare the order cancellation rate for each restaurant between the current year and the previous year. 

-- Q10. Rider Average Delivery Time 
-- Question: Determine each rider's average delivery time. 

-- Q11. Monthly Restaurant Growth Ratio 
-- Question:  Calculate each restaurant's growth ratio based on the total number of delivered orders since its joining. 

-- Q12. Customer Segmentation 
-- Question: Segment customers into 'Gold' or 'Silver' groups based on their total spending compared to the average order value (AOV). If a customer's total spending exceeds the AOV, label them as 'Gold'; otherwise, label them as 'Silver'. 
-- Return: The total number of orders and total revenue for each segment. 

-- Q13. Rider Monthly Earnings 
-- Question:  Calculate each rider's total monthly earnings, assuming they earn 8% of the order amount. 

-- Q14. Rider Ratings Analysis 
-- Question: 
-- Find the number of 5-star, 4-star, and 3-star ratings each rider has. 
-- Riders receive ratings based on delivery time: 
-- ● 5-star: Delivered in less than 15 minutes 
-- ● 4-star: Delivered between 15 and 20 minutes 
-- ● 3-star: Delivered after 20 minutes 

-- Q15. Order Frequency by Day 
-- Question: Analyze order frequency per day of the week and identify the peak day for each restaurant. 

-- Q16. Customer Lifetime Value (CLV) 
-- Question: Calculate the total revenue generated by each customer over all their orders. 

-- Q17. Monthly Sales Trends 
-- Question: Identify sales trends by comparing each month's total sales to the previous month. 

-- Q18. Rider Efficiency
-- Question: Evaluate rider efficiency by determining average delivery times and identifying those with the lowest and highest averages. 

-- Q19. Order Item Popularity 
-- Question: Track the popularity of specific order items over time and identify seasonal demand spikes. 

-- Q20. City Revenue Ranking 
-- Question: Rank each city based on the total revenue for the last year (2023).
